### ISSUE TITLE
快速选项

### ISSUE THREAD

**Issue by ledvip** [ninja33/ODH#10]
快速选项很好用，可以方便地切换词典，一般用不同的词典时，制作的卡片会希望放到不同的牌组里，所以从用户的角度最好在快速选项里同时放上牌组名称和词典切换；相反取词热键栏相比较却没有那么常用，因为直接选取文本就可以取词了，可以考虑不用放在快速选项里。谢谢！

**Comment by ninja33** [comment]
谢谢提出建议。会考虑在下一版本更新时，把牌组名称加入快速选项。

根据你的使用习惯：
如果你是常关热键习惯鼠标取词的，为了在网页链接等不可鼠标点击的文字上取词，需临时开启。
如果你是常开热键习惯按键取词的，在编辑文本时，Shift切大小写，Ctrl c/v 复制粘贴 会失效，需要临时关闭。
这是热键放在外面快捷选项的原因。

**Comment by ninja33** [comment]
fixed in 47d905a

**Comment by ledvip** [comment]
非常迅速，已经看到更新了！安卓版的划词助手，如果能加入cncn词典那就太好了，因为除了学习各种外语之外，我们自己的汉语也要更好地掌握。推荐http://hanyu.baidu.com/  百度汉语，大公司比较全面和长期稳定。非常感谢！

**Comment by ninja33** [comment]
你好。安卓划词助手不是我开发的。

另外，插件已经自带汉语词典：汉典，可用脚本代码cncn_Zdic（想调用最新版脚本可用lib://cncn_Zdic） 调用。

**Comment by ledvip** [comment]
了解了，那个安卓划词助手的作者也是受老黄的启发。汉典词典已经在用了，能在电脑上划词做中文卡片，很赞👍！
