### ISSUE TITLE
Ignore space characters in phrases when embolding the expression in the sentence field

### ISSUE THREAD

**Issue by skygate2012** [ninja33/ODH#115]
![1](https://user-images.githubusercontent.com/7148976/65104160-1abf1c00-da03-11e9-852c-54a48058180d.png)
![2](https://user-images.githubusercontent.com/7148976/65104159-1abf1c00-da03-11e9-822f-bca20ae3fe72.png)
![3](https://user-images.githubusercontent.com/7148976/65104161-1b57b280-da03-11e9-8bfe-aa7442e17d6d.png)
Is it possible to leave the space characters out of the `<b>` tag so the space would be shown (like image 2) when studying notes? This is particularly helpful to indicate that the expression is a phrase with separate words.

**Comment by ninja33** [comment]
sure, it's implemented in commit ccd818d777abef4a70da8334013c5f1c5fe76e19
but you have to wait next release, or fork your own version in developer mode.
