### ISSUE TITLE
求助：Anki 划词制卡助手和在线词典助手在Windows 10, Version 1909系统里无法制卡

### ISSUE THREAD

**Issue by sszhe** [ninja33/ODH#128]
如题。
之前win7里制卡是正常的。
现在重装了系统，Chrome插件、Anki PC客户端及Ankiconnect插件都确认安装好了。打开助手-anki连接选项-词汇模板映射表-牌组名称和模板名称显示黑色。在网页上取词一直显示灰色+。
PC客户端2.0、2.1和两个助手都分别试过，Chrome其它插件也全部关闭，始终搞不定，折腾一上午了，无解。

**Comment by ninja33** [comment]
选项下拉菜单黑色是chrome的bug，可以看看其他issue里的回答。如果下拉菜单没配置好，前段制卡当然是灰的


发自我的iPhone

**Comment by sszhe** [comment]
thanks，我太一根筋迷恋Chrome了，在Firefox里试试果然可以。
