### ISSUE TITLE
感谢大神开发的好工具，请问有没有办法添加自己本地的词典包？

### ISSUE THREAD

**Issue by relaxbao** [ninja33/ODH#144]
感谢大神的好工具，已经超级强大了，帮我解决了大问题！

请问可以加载本地的词典包吗？

当然没有也没事，我自己添加就成，如果有就太好啦~

**Comment by ninja33** [comment]
本地词典需要配合mdx server成为一个本地的词典网站。然后加载自定义脚本去解析这个本地词典网站。

发自我的iPhone

**Comment by relaxbao** [comment]
感谢大神及时回复，太棒啦~ 我去试试

**Comment by NewOneTcm** [comment]
> 感谢大神及时回复，太棒啦~ 我去试试
请问一下，你做出来了吗？
怎么操作，能分享一下吗？

**Comment by relaxbao** [comment]
> > 感谢大神及时回复，太棒啦~ 我去试试
> > 请问一下，你做出来了吗？
> > 怎么操作，能分享一下吗？

你可以看下这个，貌似要在本地一直启动这个服务，加载本地词典包
https://github.com/ninja33/mdx-server

然后启动了之后，要自定义脚本解析本地词典网站
https://github.com/ninja33/ODH/blob/master/doc/development.md

我安装了md server，但是觉得解析本地词典网站有一丢丢麻烦，我就没有研究了。

安慰一下自己，我的目标是记住这些词。所以有些重要的，我就重新copy一下、也算重复记忆了-_-

**Comment by KnIfER** [comment]
我也实现了个 mdx server，现在还可以搬到手机里，可以用我的 mdx server 么……

**Comment by KnIfER** [comment]
我把内网服务器IP填到书签里了，然后插件就可以查询，书签存在C盘的一个文件里，所以以后acrobat也可以用一样的IP。

 http://localhost:8000/{word} 这地址太简单了，最好中间加些东西，比如
 http://localhost:8000/query/{word} 就很好。
