### ISSUE TITLE
希望能通过“在独立窗口搜索剪贴板内容”等方式，实现插件全局可用

### ISSUE THREAD

**Issue by Crawling-Snail** [ninja33/ODH#154]
有时会阅读英文PDF，因为需要做些标记注释，所以喜欢用Acrobat这样的软件，而不是用浏览器。
所以希望能在全局范围内使用ODH这个插件。

我了解到“沙拉查词-聚合词典划词翻译”这个插件能够通过“在独立窗口搜索剪贴板内容”方式来实现浏览器外的划词翻译[1]，进一步如果结合Quicker，就能实现更加自动化的全局翻译[2]。

看了下插件设置，大佬目前好像没有做类似的功能，请问大佬有开发出类似的功能的计划么？

[1][沙拉查词-浏览器外划词](https://saladict.crimx.com/native.html)
[2][文献翻译利器：沙拉查词+ Quicker，这或许是 Windows上最强的聚合翻译方案 - 小铅笔的文章 - 知乎](https://zhuanlan.zhihu.com/p/106650743)
[3][沙拉查词github网址](https://github.com/crimx/ext-saladict)

**Comment by 8ctive** [comment]
不光浏览网页和阅读的时候会遇到生词，其他场景也有很多，比如软件界面、电影字幕等。不如加个手动输入单词的方式，这样适用范围更广。

**Comment by JianxingHan** [comment]
现在Quicker社区有人做出了差不多满足上述需求的脚本，有需求的可以去看下，下面我给出关键网址，并摘录一些重要内容。
脚本地址（内有演示动画）：[ODH在线词典助手](https://getquicker.net/Sharedaction?code=b92e26d7-628e-4b4d-c4c6-08d7f7cf8b53&fromMyShare=true)

大致实现方法：使用Chrome App模式下的窗口来承载ODH插件窗口，然后通过初始化时用户的手动调整，使Chrome窗口恰好能够完整显示ODH窗口，之后每次执行动作来查词时，都将以这个大小打开chrome窗口(姑且称之为ODH父窗口)。
另外，鉴于ODH父窗口作为类似弹窗式的显示方式，在设定其弹出位置时考虑了如下两个因素：
1. 弹窗出现在鼠标附近
2. 完整显示在屏幕中，不超出屏幕边界

**Comment by moncoeur** [comment]
我有类似的需求，不过我只要能有一个可以手动输入单词查询的地方就行了，现在只能取页面上的词不是太方便，试过本地的html文件也取不了词。

**Comment by JianxingHan** [comment]
> 我有类似的需求，不过我只要能有一个可以手动输入单词查询的地方就行了，现在只能取页面上的词不是太方便，试过本地的html文件也取不了词。

我上面提到的quicker脚本（quicker里叫「动作」）应该能实现你的需求，只要执行动作前不要选中文本就行了，会提示你自己输入一个单词，演示动画里也有这部分，可以先去看看。

另外，本地html取不了词应该是你没有开启ODH的「允许访问文件网址」，这一点在quicker动作页也有说到。如下图：
![image](https://user-images.githubusercontent.com/52602531/82108450-059cb780-9761-11ea-87af-544c69123d28.png)

总之呢，我觉得你好好看看[动作地址](https://getquicker.net/Sharedaction?code=b92e26d7-628e-4b4d-c4c6-08d7f7cf8b53&fromMyShare=true)应该就行了
