### ISSUE TITLE
请问如何关闭双击取词功能

### ISSUE THREAD

**Issue by billzhuang** [ninja33/ODH#16]
我设置了alt取词，我的理解是按住alt加鼠标左键可以取词，但我发现现在双击也会取词。

请问如何关闭，谢谢

**Comment by billzhuang** [comment]
谢谢你的答复，我已意思就是能否在选中时不启动翻译，当且仅当热键+鼠标悬停时取词。

原因之一，很多时候我选择一个词，或者双击造成的一个选词，可能只是我的不良阅读习惯。

而更常见的一个场景是，我在一个textbox里输入一个词，后来发现输错了，常规的操作是双击然后按del键，重新输入，在这个场景下，我必然不期望弹出取词。

**Comment by ninja33** [comment]
这么说吧，所谓的热键取词，也是选中翻译，只是插件自动帮你把鼠标下的单词选中了。所以如果去掉选中翻译，这个插件就不工作了。

为什么一定要选中翻译，是因为只有鼠标的人工选择(作为选中的一个特例)，才可以解决词组的问题。因为词组的复杂性，插件无法自动判定选多少词。

编辑场景的选择翻译是一个已知的冲突，目前没法避免。插件的主要使用场景时阅读小说和新闻。一般而言，在偶尔需要编辑的时候，可在快速选项处禁用插件。

**Comment by r888800009** [comment]
textbox或textarea不popup在使用搜尋引擎的時候是很實用的功能。#17
不過我查了Selection的文檔好像沒有找到比較簡單判斷textbox或textarea，我只能抓到dev。
也許可以設定一個開關熱鍵來控制插件是否啟用會不會是更簡單的方法？

**Comment by ninja33** [comment]
已修复 input text 和 input textarea 中弹出窗口的问题 by 5fd4c38
