### ISSUE TITLE
内置的柯林斯词典是怎么制作的

### ISSUE THREAD

**Issue by cyj98** [ninja33/ODH#165]
请教下有什么好的制作内置词典的方法。
我想制作一个习语的内置词典，我能想到的只是下载mdx用mdx export后用爬虫工具抓取，不过我那个词典排版爬虫不好写。

**Comment by ninja33** [comment]
用mdx转换导出工具，先把mdx文件转换成一行一个词条的txt文本。然后用自己熟悉的语言，转换成javascript可用的json格式，在插件加载的时候，加载这个json，就可以按照词条键值索引了

发自我的iPhone

**Comment by cyj98** [comment]
谢谢，明白了，没注意到要一行一行看。
