### ISSUE TITLE
怎麼讓單字在句中為斜體？

### ISSUE THREAD

**Issue by johan456789** [ninja33/ODH#174]
我改了ODH的牛津script，[這行](https://gist.github.com/johan456789/2889619f19802bb5a6ffc43973fe233e#file-encn_oxford_custom-js-L64)加了`<i></i>`，但是單字還是只有粗體。

請問要怎麼改呢？一時研究不出來。

是網頁裡的句子，不是字典的例句。

**Comment by ninja33** [comment]
网页句中单词加粗的代码不在词典脚本里，
在 ODH/src/fg/js/text.js 这个文件的91行和93行

**Comment by johan456789** [comment]
謝謝，我會了。

For future reference:

用[這裡](https://stackoverflow.com/a/16688027/6306190)寫的方法下載插件，然後更改91行和93行

https://github.com/ninja33/ODH/blob/a8b1fe55f44f9577f64d9c72c991c785e160f64d/src/fg/js/text.js#L91-L93
