### ISSUE TITLE
Add URL as hyperlink

### ISSUE THREAD

**Issue by johan456789** [ninja33/ODH#178]
現在ODH加入到Anki卡片的URL是純文字，如果能弄成超連結會更方便些。

**Comment by ninja33** [comment]
插件只是保留了原始信息，怎么展现是anki模板的功能

**Comment by johan456789** [comment]
AnkiConnect [支援HTML](https://github.com/FooSoft/anki-connect/issues/191), 所以只要加上HTML碼就好了。在Anki，貼上一個URL本來就會自動變成超連結（至少在Mac上是這樣），所以我想這個行為可能更適合作為預設。

<details>
<summary>Click to show request</summary>

```json
{
    "action": "addNote",
    "version": 6,
    "params": {
        "note": {
            "deckName": "Default",
            "modelName": "Basic",
            "fields": {
                "Front": "Example",
                "Back": "<a href=\"http://example.com\">http://example.com</a>"
            },
            "tags": []
        }
    }
}
```

</details>


https://user-images.githubusercontent.com/14802181/104206165-30631b00-546a-11eb-98fd-c770cd7ea717.mov

**Comment by ninja33** [comment]
技术上不是问题，如果是短的url还好，但如果浏览时产生的url很长，其实不太适合放在anki学习界面。

而且这样做，也违背了内容和展示分离的原则，我之前做的anki模版有很多都是内嵌url，展示的时候会显示“原文网址”或者“url” 字样，点击后跳转该网页

发自我的iPhone
