### ISSUE TITLE
Monolingual dictionary

### ISSUE THREAD

**Issue by lyctw** [ninja33/ODH#179]
Thank you for providing such a good application, I really enjoy to use it for a better reading experience.
Could you please add monolingual dictionary (for example, Cambridge EN->EN) in the options?

**Comment by ninja33** [comment]
there is an en->en collins online dictrionary shipped with extension but not enabled by default
you can enabled it in optiion->script tab
![image](https://user-images.githubusercontent.com/20181220/104194142-e3784800-545b-11eb-97d9-e083b937a4a6.png)

btw, you also can select 'Monolingual' in genral option tab, so when you use en->cn dictionary, it will display en->en only
![image](https://user-images.githubusercontent.com/20181220/104194223-f854db80-545b-11eb-86fd-c9a06455b96b.png)

**Comment by JiaChen-Zeng** [comment]
I found a problem. I'm using EN->CN dictionary with the monolingual setting. When adding an Anki card, it will wrongly include Chinese translations.
