### ISSUE TITLE
可不可以一次添加单词的所有释义呢？

### ISSUE THREAD

**Issue by TonWang** [ninja33/ODH#18]
当单词有多义的时候点击+号就只会添加一个意思，如果点其他释义的+号就会制新的卡，可不可以像anki划词助手那样一次性添加所有释义呢？

**Comment by ninja33** [comment]
选项里把那个“多义”映射到你拍组的解释字段就好了。

**Comment by TonWang** [comment]
果真可以，多谢回复！
