### ISSUE TITLE
Ankiweb无法登陆

### ISSUE THREAD

**Issue by Yulin-Rog** [ninja33/ODH#181]
老黄，就是这一两周我发现我的Ankiweb无法登陆了，无论是重新安装extension，还是重启都无法解决。是因为Chrome最近版本大更新的问题吗，还有就是Ankiconnect也一直掉链，很难连接上，想求助老黄康康

**Comment by ninja33** [comment]
ankiweb的接口变化了。我会更新一个版本解决这个问题

**Comment by ninja33** [comment]
fixed by 31e170c
