### ISSUE TITLE
[Feature Request] 希望增加制卡到remnote的功能

### ISSUE THREAD

**Issue by blackwint3r** [ninja33/ODH#192]
[remnote](https://www.remnote.io/import/anki)是一个革命性的笔记软件，具有间隔重复功能，在很多方面都超过了anki。现在它已经取代anki成为我的主力。现在的问题就是您在[这里](https://zhuanlan.zhihu.com/p/25866272)介绍的workflow我不知道该怎样迁移到remnote。
remnote虽然有一款[chrome插件](https://chrome.google.com/webstore/detail/remnote-clipper/ohidiiabdhnlgcaidgndbdbjlhngeboj)，不过是用来给网页做笔记用的。

请问能否增加选词制卡发送到remnote的功能？或者，如果我要改造您的插件以实现这个功能，应该怎么做？能给我一些提示吗？
（remnote有简单的restful api ，参见[这里](https://www.remnote.io/api)）

**Comment by ninja33** [comment]
好的。有时间我会去看看remnote怎么用，然后设计一个接口。

如果你要自己设计的话。在backend.js里有个target的类成员，可以被赋值一个含有addNote成员函数的类。当需要保存卡片时，只要调用target.addNote就可以了。所以当target =ankiweb那么就是保存到ankiweb网站，如果target=ankiconnect就是保存到ankiconnect，你也可以自己编写一个remnote类，那么当target=remnote时，就是保存到remnote

有任何问题可以在此留言继续讨论

发自我的iPhone

**Comment by blackwint3r** [comment]
谢谢，有空我去研究下。
