### ISSUE TITLE
extension options中不显示ankiconnect options

### ISSUE THREAD

**Issue by yett1873** [ninja33/ODH#218]
您好，安装ODH后页面里始终没有出现说明文档里的ankiconnect options选项，如下图所示，此前使用您的anki划词制卡助手时一直能正常通过ankiconnect制卡，看了别的issues里好像都没出现过这个问题。希望能帮忙看看，感谢！

![image](https://user-images.githubusercontent.com/75569851/147884331-fcf08e25-7d28-4aa5-8017-b4c7759abb8a.png)

![image](https://user-images.githubusercontent.com/75569851/147884443-cc79a701-fca9-48c1-b5fa-ebfcc075cc1b.png)

**Comment by ninja33** [comment]
@yett1873 ankiconnect options已经移到service option里去了

**Comment by yett1873** [comment]
好的，谢谢！
