### ISSUE TITLE
MDX_Server，本地查词失败

### ISSUE THREAD

**Issue by AsterShion** [ninja33/ODH#219]
想用在线词典助手查询本地的朗文5双解词典，可以正常打开“http://127.0.0.1:8000/friend” 这样的页面。
但是双击网页单词的时候，无法弹出查词的对话框。但是切换成牛津、柯林斯、剑桥几个英汉词典的时候却可以正常使用，能弹出查词对话框。

错误提示是这样的：
![odh_error](https://user-images.githubusercontent.com/62572820/147948664-0c399996-44c0-4d38-abe8-094852a41920.png)

chrome浏览器为目前的最新稳定版：Version 96.0.4664.110
已经开启在线词典助手在chrome中的“Allow access to file URLs”选项

ODH版本为：Version 0.9.2

还有一个比较奇怪的事，就是导入“encn_LDOCE5MDX”脚本的时候，最后在右上角的ODH中显示的脚本名称为“enen_LDOCE5MDX”，我不懂是否有什么关联，或是只是显示错误而已。这个信息不知道对解决问题能否有所帮助。

我测试过本地的三个MDX文件，朗文5双解，朗文6，朗文6双解，选项中也分别换成了朗文5和朗文6的脚本，依旧无法弹出查词对话框。很是头疼，请问要怎样解决问题呢？

**Comment by ninja33** [comment]
先在浏览器里看看，能不能访问这个mdx server加载的不同词典。浏览器里能访问，至少mdx server是OK的，也证明mdx文件本身的编码也OK

再有问题，就要看odh插件的后台。需要进入chrome后台插件管理详情页，打开odh的bakcend.html，观察chrome开发者页面里network tab里，odh往mdx server具体发送了什么请求

还有就是你这个脚本，是自己按照插件里带的朗文6mdx改的吧。可能这个脚本也有问题。因为400 bad message request表明脚本往mdx server发送的查询消息有问题

**Comment by AsterShion** [comment]
> 先在浏览器里看看，能不能访问这个mdx server加载的不同词典。浏览器里能访问，至少mdx server是OK的，也证明mdx文件本身的编码也OK
> 
> 再有问题，就要看odh插件的后台。需要进入chrome后台插件管理详情页，打开odh的bakcend.html，观察chrome开发者页面里network tab里，odh往mdx server具体发送了什么请求
> 
> 还有就是你这个脚本，是自己按照插件里带的朗文6mdx改的吧。可能这个脚本也有问题。因为400 bad message request表明脚本往mdx server发送的查询消息有问题

脚本不是自己改的，虽然正在学习python，可是仍然没有能力写出这样的脚本。。
重新下载了另一个版本朗文6的英英词典后，发现确实是mdx文件的问题，可以正常弹出查词对话框，添加单词了。

目前使用英英词典仍然感到很吃力，您是否有支持ODH的朗文双解词典呢？我找到的朗文5、朗文6的双解词典版本，都无法在ODH中正常使用。

**Comment by AsterShion** [comment]
> 先在浏览器里看看，能不能访问这个mdx server加载的不同词典。浏览器里能访问，至少mdx server是OK的，也证明mdx文件本身的编码也OK
> 
> 再有问题，就要看odh插件的后台。需要进入chrome后台插件管理详情页，打开odh的bakcend.html，观察chrome开发者页面里network tab里，odh往mdx server具体发送了什么请求
> 
> 还有就是你这个脚本，是自己按照插件里带的朗文6mdx改的吧。可能这个脚本也有问题。因为400 bad message request表明脚本往mdx server发送的查询消息有问题

解决了，确实是mdx文件的问题，更换后可以正常使用了，谢谢！
