### ISSUE TITLE
怎么查看 {{sentence}} 的翻译

### ISSUE THREAD

**Issue by unix2dos** [ninja33/ODH#222]
选词的时候，会把原句给加入。但是想把原句的翻译一起加入。

**Comment by ninja33** [comment]
选柯林斯词典（不是内置的那本），这个其实是有道词典的在线版本。然后用鼠标选中整个句子，就是整句翻译了

**Comment by unix2dos** [comment]
> 选柯林斯词典（不是内置的那本），这个其实是有道词典的在线版本。然后用鼠标选中整个句子，就是整句翻译了

不只是在网页上查看句子的翻译，而是想把整个句子的翻译，填入到odh模板里。

**Comment by unix2dos** [comment]
新增了一个字段，安装了一个谷歌翻译插件解决。
