### ISSUE TITLE
成功添加卡片后背单词时是空白的，编辑卡片可以看到有内容

### ISSUE THREAD

**Issue by effycoco** [ninja33/ODH#226]
成功添加卡片后背单词时是空白的，但是编辑卡片的话glossary明明有内容
<img width="626" alt="截屏2022-02-13 下午10 10 23" src="https://user-images.githubusercontent.com/28746484/153756955-e0516d05-0f85-496a-8b6f-d2ceac9ec901.png">
<img width="1012" alt="截屏2022-02-13 下午10 10 52" src="https://user-images.githubusercontent.com/28746484/153756968-6c0b706e-af56-4667-afe3-1792153168dd.png">

**Comment by ninja33** [comment]
字段里内容进去了，就表明插件没问题的。就是那个模版，是antimoon的模版。所以他缺省状态是不给释义的。最下面那个空白的点一下。不然就把释义放在collins字段里不要放在glossary里

**Comment by effycoco** [comment]
多谢，解决了，原来glossary相当于原来的译文字段，可以点击的
