### ISSUE TITLE
在 ankiconnect 已安装且 anki 运行的情况下显示 anki 未连接

### ISSUE THREAD

**Issue by gxglls** [ninja33/ODH#229]
#### 问题如下图
![image](https://user-images.githubusercontent.com/12667277/156914768-9a33fbfa-5128-4313-b818-8f585a3de711.png)

#### 环境
MacOS. 本地 anki 端口测试正常
```
lzy@MacOS.local:/Users/lzy/anki $ curl localhost:8765 -X POST -d '{"action": "deckNames", "version": 6}'
{"result": ["test", "\u4e0b\u8f7d/\u53cc\u51fb\u6253\u5f00/\u81ea\u52a8\u5bfc\u5165anki\u4f5c\u4e3a\u6a21\u677f", "\u6211\u7684chrome\u8bed\u5883\u751f\u8bcd\u5e93", "\u7cfb\u7edf\u9884\u7f6e", "\u7f8e\u56fd\u5f53\u4ee3\u82f1\u8bed\u8bed\u6599\u5e93", "\u82f1\u8bed\u8bcd\u6839\u4e0e\u5355\u8bcd\u7684\u8bf4\u6587\u89e3\u5b57"], "error": null}%
```

anki 打开 http 日志后，未看到插件链接相关的日志，请问如何查看插件的日志或者其他的排查思路？ 谢谢

#### 其他补充
把输出选项从 Ankiconnect 切换到 None 再切换回来后能成功，但是持续时间很短暂就会断掉，且不自动重连

**Comment by ninja33** [comment]
在chrome插件管理页，打开odh插件详情，点击background.html，然后按F12看network页面，看看插件是怎么和本地8765端口通讯的

**Comment by ninja33** [comment]
> #### 其他补充
> 把输出选项从 Ankiconnect 切换到 None 再切换回来后能成功，但是持续时间很短暂就会断掉，且不自动重连

哦。刚看到你还有个补充。那个是ankiconnect在macOS上使用的常见问题。你可以去ankiconnect GitHub主页查查。有个命令执行一下

**Comment by gxglls** [comment]
目前取消后台模式后看上去正常运行了，十分感谢！
