### ISSUE TITLE
[macOS] can't add anki card

### ISSUE THREAD

**Issue by emacsbliss** [ninja33/ODH#230]
Got following error (from manage extension/errors) when click the green add button from popup:
```
cannot create note because it is empty
```

ankiconnect is latest version and extension has been configured to use the correct deck from anki.

**Comment by ninja33** [comment]
except the deck, may I know if the note type and fields was correctly mapped?

you can capture an extension screen here

**Comment by emacsbliss** [comment]
![Screen Shot 2022-03-06 at 12 05 03 PM](https://user-images.githubusercontent.com/65474902/156955120-1d53ba22-4bb3-42c6-bac9-27be6388fd54.png)

**Comment by ninja33** [comment]
well, please map front to expression, and map "back" to "definition" only, leave other mapping blank, and try again.

**Comment by emacsbliss** [comment]
cool, that works!! thanks a lot!
