### ISSUE TITLE
data directory is missing under bg in this repo

### ISSUE THREAD

**Issue by emacsbliss** [ninja33/ODH#231]
I'm not quite clear where does data directory come from, but when I tried to load the extension into chrome, chrome complains there is no file `data/wordforms.json` and `data/collins.json`..

Not sure if those files are generated, but I found them in the installation directory and looks like `collins.json` size is relatively big.

however without these files, one can't really develop and run this extension locally..

I may have misunderstood the intention for these files completely..

**Comment by ninja33** [comment]
yes, these word data files are too big to be uploaded to github, but it is included in web store extension package.

**Comment by emacsbliss** [comment]
ok, thanks for clarification
