### ISSUE TITLE
无法播放 http 服务器上的发音文件

### ISSUE THREAD

**Issue by z-gong** [ninja33/ODH#232]
我使用了自定义脚本，词典数据和发音都托管在一个 http 服务器上，脚本返回的 notes.audios 是一组完整的 http:// 开头的url，但是在播放发音的时候，ODH 会试图访问 https:// ，结果就被服务器拒绝了

![图片](https://user-images.githubusercontent.com/379616/157823013-eeff4379-82f0-40bd-8cb6-35dd787166e4.png)

**Comment by ninja33** [comment]
之前Google是允许插件对外部进行http访问的。现在完全不允许了，否则不让上架。所以，只能用https
