### ISSUE TITLE
修改AnkiConnect端口

### ISSUE THREAD

**Issue by xuehao** [ninja33/ODH#235]
问题：默认端口8765无法启用，改用其他端口后，插件不识别
建议：能否增加修改默认端口配置

**Comment by ninja33** [comment]
8765端口没法用，一般是因为上一次anki没退出干净，可以尝试重启电脑。

至于ankiconnect定制化端口，这个可以在下一版本加上，但同时用户也要自己有能力改ankiconnect的端口，这个涉及改动ankiconnect插件里的python文件。

**Comment by xuehao** [comment]
我后来发现了，真的很隐蔽。端口占用情况，解决方法如下，供大家参考：

## 检查是否有程序占用

CMD 使用如下命令：

```
netstat -ano | findstr ":8765"
```

如果被占用杀掉相应程序即可。

## 系统保留端口

上述方法始终没发现占用端口，后来查资料说是Win10 Hyper-V 系统保留了。

CMD 检查默认保留端口：

```
netsh interface ipv4 show excludedportrange protocol=tcp
```

如果发现8765在这个列表里面，可以根据需要适当修改：

```
# start 起始端口  num 表示可用端口数     按自己的需求来
netsh int ipv4 set dynamicport tcp start=30000 num=16383
```

**Comment by ankopala** [comment]
> 8765端口没法用，一般是因为上一次anki没退出干净，可以尝试重启电脑。
> 
> 至于ankiconnect定制化端口，这个可以在下一版本加上，但同时用户也要自己有能力改ankiconnect的端口，这个涉及改动ankiconnect插件里的python文件。

您好，我使用了一阵子的ODH，它对我很有帮助！不知道现在支不支持修改端口了？我在ankiconnect的插件设置里修改了端口，并在yomitan切换端口后连接有效且稳定。不知道ODH现在有没有这个功能（我的8765端口无法监听是因为启动VPN，只要我不开VPN它就是可用的。但我需要保持网络顺畅以便浏览更多资讯。。）
