### ISSUE TITLE
通过Ankiweb制卡不能获得音频

### ISSUE THREAD

**Issue by LiYuxuanhaha** [ninja33/ODH#239]
如标题所述，通过ankiweb制卡并不能获得相应的音频文件，通过本地的Ankiconnect制卡可以

**Comment by ninja33** [comment]
这个不是插件所能决定的。odh插件只是发送一个音频文件url给相应接口。

ankiweb接口没有音频下载能力。所以不带音频。ankiconnect是在anki的桌面端运行的。所以有音频下载能力
