### ISSUE TITLE
My ODH not connected with ankiconnect

### ISSUE THREAD

**Issue by lavData** [ninja33/ODH#246]
I use Anki Linux. While my Anki app running, the ODH is not connected to ankiconnect.
![image](https://user-images.githubusercontent.com/80758144/168533354-df89aa13-7c1a-467e-955a-1705997046d0.png)
![image](https://user-images.githubusercontent.com/80758144/168533386-79e55d5d-e1e2-472e-8e62-45b94bed1434.png)

**Comment by ninja33** [comment]
Did you install "ankiconnect" addon in anki?

**Comment by lavData** [comment]
Thank you. The "ankiconnect" was updated today. I use ODH for a long time to forget checking this addon.
