### ISSUE TITLE
微信读书中取词

### ISSUE THREAD

**Issue by lwl5219** [ninja33/ODH#249]
有没有什么方案, 能够使用 ODH 在网页版微信读书中取词?

**Comment by ninja33** [comment]
试过了，没方案。微信读书为了防止文章被盗版，在页面上采取了非常复杂的混淆算法。把句子里的每个字词都打散了。所以根本选择和复制不了字词句。这个你可以自己用浏览器试试看。如果你会用浏览器开发工具，可以按F12查看微信读书页面的html文档实际内容。

ps:我自己也是微信读书的付费卡用户。没辙😓
