### ISSUE TITLE
牛津词典再次用不了，请求看看是不是脚本出了问题

### ISSUE THREAD

**Issue by yao525** [ninja33/ODH#253]
7.14号左右，选择英文单词后，牛津词典突然无法弹出释义，其他词典都是可以的。
我更换了几个浏览器，重新安装插件、Anki等等，牛津词典还是不能用
并且，不止是我一个人，身边的四位同学也是这样的情况。
这是我第一次给您留言求助，真的非常非常感谢您弄出了这个插件，我是考研党，这个插件帮助了我很多很多，身边的很多同学都在用，考研英语词义有些比较偏，牛津词典释义很全面，因此我们对它非常非常依赖。突然不能选词之后非常焦虑，在网上看了很多解决办法都无济于事，辗转找到您的账号求助，希望您看看到底是什么地方出现了问题，最后祝您一切顺意！

**Comment by ninja33** [comment]
脚本没改，查了一下，是源网站页面修改了。因为插件本身不带词典（太大装不下），所以都是从网上获取的信息。如果原网站改了，那脚本就失效了。

我已经找到问题了，会尽快修复。

**Comment by yao525** [comment]
> 脚本没改，查了一下，是源网站页面修改了。因为插件本身不带词典（太大装不下），所以都是从网上获取的信息。如果原网站改了，那脚本就失效了。
> 
> 我已经找到问题了，会尽快修复。



> 脚本没改，查了一下，是源网站页面修改了。因为插件本身不带词典（太大装不下），所以都是从网上获取的信息。如果原网站改了，那脚本就失效了。
> 
> 我已经找到问题了，会尽快修复。

**Comment by yao525** [comment]
非常感谢！

**Comment by ninja33** [comment]
插件已经修复了 (commit 12aa254)，但是还没推送到chrome商店。

如果你这边着急用的话，可以加载云端脚本，会自动加载已经在github上修复的脚本。具体步骤如下：

![image](https://user-images.githubusercontent.com/20181220/179784326-80f19b82-17ea-42d0-aa3f-08dade78591a.png)

**Comment by yao525** [comment]
好的好的，十分感谢

**Comment by yao525** [comment]
有点小问题哦，按照步骤弄完之后，快速选项的下拉菜单里没有牛津词典，但是在设置里是确认勾选并保存的。
![image](https://user-images.githubusercontent.com/109365380/179804832-f7eb1334-57b6-4f4b-93f1-5cbe4d7df8fc.png)
![image](https://user-images.githubusercontent.com/109365380/179804933-9eac109f-ba93-4ced-9522-f1ecc6b5b1d9.png)

**Comment by ninja33** [comment]
chrome商店已经审核通过了。如果还没有被自动推送，可以自己手工更新一下


![image](https://user-images.githubusercontent.com/20181220/180171772-d03ba4ae-8ac2-44e6-87bc-00b781c43a63.png)
