### ISSUE TITLE
作者大大修复牛津词典了吗?

### ISSUE THREAD

**Issue by Hustcketlyj** [ninja33/ODH#254]
一天不用都不行哈哈

**Comment by Hustcketlyj** [comment]
@ninja33 按照步骤操作了，就没有牛津词典这个选项了

**Comment by ninja33** [comment]
嗯。知道了。和隔壁一样。github的远程词典没有调用成功。那就等chrome商店推送吧

**Comment by ninja33** [comment]
新版本我已经上传Google商店了。还在审核中。不知道啥时候

**Comment by ninja33** [comment]
chrome商店已经审核通过了。如果还没有被自动推送，可以自己手工更新一下


![image](https://user-images.githubusercontent.com/20181220/180171772-d03ba4ae-8ac2-44e6-87bc-00b781c43a63.png)
