### ISSUE TITLE
试用了下百词斩图文词典，加载不出来

### ISSUE THREAD

**Issue by closernow** [ninja33/ODH#255]
就是取词的时候没有释义弹出来，试了朗文也是一样，不知道哪里没有设置对，勾选了云端并按照1234步骤操作了

**Comment by ninja33** [comment]
百词斩应该早就挂了。我有时间看看。不行就去掉了。在线词典一般源网站变化后，这个脚本就失效了。

如果想看插件是否正常工作，首先就是看那个内建的柯林斯词典是否OK，如果OK，那插件本身没问题。大概率是脚本失效。

**Comment by closernow** [comment]
那应该是失效了，其他的可以
