### ISSUE TITLE
Issue resolved (user--my--mistake)

### ISSUE THREAD

**Issue by cerf-tombant** [ninja33/ODH#256]
[Edit: I fixed the issue, was user error (that is to say, my fault not the developer)!]

**Comment by ninja33** [comment]
from source of ODH https://github.com/ninja33/ODH/tree/master/src/dict

It never shipped with fr-fr dictionary. do you mean en-fr or fr-en dictionary?

**Comment by cerf-tombant** [comment]
For 2 years I have used your (amazing) extension to get FR dictionary definitions. I would double click a French word and it would give me the French definition and the ability to add to Anki (I do not recall which French dictionary this was). Since updating the extension, now my only options are FR->EN or EN->FR dictionaries, which is not ideal for those (like myself) who create monolingual Anki decks.

**Comment by cerf-tombant** [comment]
Nevermind, I see what happened. Somehow my dictionary changed to Collins FR->EN. I was using Cambridge FR->EN, which actually gives you FR->FR functionality as well! Sorry for adding any confusion and I will delete this Github thread since there is in fact no issue. Thanks again for your extension!!!
