### ISSUE TITLE
快速切换不同的制卡场景

### ISSUE THREAD

**Issue by lucerna-gelu** [ninja33/ODH#271]
通常来讲，制作的卡片可以分为两类：

- 单词卡片，又可以细分为带拼写的和不带拼写的
- 句子卡片，用于记录某些有意思的句子，某些惊艳的表达方式

通常我会将这两种卡片放到不同的deck中
如果我想切换制作这两种卡片，那么我首先需要切换deck、tag、词典
![image](https://user-images.githubusercontent.com/66851780/197370362-dd5d7866-f124-4e49-a43a-3292db59a684.png)
然后切换卡片模板
![image](https://user-images.githubusercontent.com/66851780/197370438-38f2c1eb-08e8-4aed-b4aa-41286492655e.png)

如此一来，切换就变得非常繁琐了，有没有一种方式可以快速切换呢
或者是添加一种预设功能，只要切换预设即可一键切换

**Comment by ninja33** [comment]
可以事后整理。一天能有记录几十个单词或者句子已经不错了。事后工作量也不大。

划词的时候不打断阅读是关键，不要作太多的操作

**Comment by lucerna-gelu** [comment]
> 划词的时候不打断阅读是关键，不要作太多的操作

第一遍阅读的时候这个的确很重要，用于锻炼自己的阅读速度，我习惯在第二次阅读时制卡，这其中就包含了单词卡和句子卡

其实一个很好的解决方法就是把anki的制卡窗口打开在旁边，直接在anki里面制句子卡，因为句子卡只需要原句copy过去就行，odh只用来制单词卡
