### ISSUE TITLE
制卡内容缺失，但网页查词结果正常

### ISSUE THREAD

**Issue by mutiann** [ninja33/ODH#281]
如标题，制卡后anki内的卡片只有单词、网页中的context和音频，但网页上显示的查词结果正常地包含了释义、例句等信息，无论使用AnkiConnect还是AnkiWeb都是如此。
使用的是Chrome 108，Anki 2.1.54，Windows 10。不清楚是我的使用方式不对还是遇到了什么bug，请问作者可以check一下吗~

**Comment by ninja33** [comment]
你后台选项处的anki 选项里，模版怎么配置的，能截个图看一下吗？

**Comment by mutiann** [comment]
![image](https://user-images.githubusercontent.com/13358837/209535998-a9f34fec-1b6d-4a8f-a07e-ab97c26b5a37.png)
![image](https://user-images.githubusercontent.com/13358837/209535670-441ff62e-e03d-4ca4-a811-a5726a703956.png)
（其它的配置我也试过，一样有问题；Scripts Options用的就是默认的设置，ODH版本是0.9.5）

查词界面显示出来是这样：
![image](https://user-images.githubusercontent.com/13358837/209535611-7eaeede3-8cab-4728-a343-16222868e7c6.png)
但是Anki里只有这样：
![image](https://user-images.githubusercontent.com/13358837/209535804-c52f2b49-adea-465a-accb-6fdf7e302ccd.png)

**Comment by ninja33** [comment]
你模版用的是最简单的basic模版。模版的“正面”和“反面”字段应该只能用于映射一个内容。比如expression-> 正面，definition->反面。他的意思是把expression也就是词头放到模版正面字段，把definition也就是释义放到模版反面字段

你如果想放更多内容，要在模版里建更多字段，你可以在这里找找
https://www.laohuang.net/20180213/online-dictionary-helper/
我提供了一个odh模版的。字段映射也按照图片里的设

**Comment by mutiann** [comment]
明白了，感谢~

**Comment by mutiann** [comment]
> 

请问有类似于给出释义拼写单词的模板吗？
