### ISSUE TITLE
俄语词性问题

### ISSUE THREAD

**Issue by person2217** [ninja33/ODH#289]
老黄，你好。我最近在学俄语，非常感谢能使用此优秀软件加快了我制卡进度。
但因俄语语法较复杂，希望俄语制卡时能收录更多关于该单词信息。

1.词性问题，是否能增加取录范围，方便记忆？
通常划词助手收录的是千亿的简洁涵义，能否增加下方行业示意中的词性和后方的变位变格？
![无标题](https://user-images.githubusercontent.com/106829332/217171125-7e2b8adf-ea16-4aa5-9f4c-8fc2a8592fc8.png)
![image](https://user-images.githubusercontent.com/106829332/217171227-7f280e87-6fde-440b-a5e8-6e600760f240.png)

2.单词制卡是否能增加单词颜色？（红色为重音，类似汉语拼音的音标）
![image](https://user-images.githubusercontent.com/106829332/217169672-2b46a3a3-162b-43be-9149-beede737b341.png)

非常感谢！

**Comment by ninja33** [comment]
俄语词典还能用啊？没想到。

我不懂俄语。所以需要你这样懂的提意见呢。我回头去看看

**Comment by person2217** [comment]
好的。坐等

**Comment by person2217** [comment]
另外因为动词变格较多（一个动词最多144个变格），如果添加上了，需要在模板上默认折叠，thx

如果需要的话可以私信加我qq       ：）

**Comment by person2217** [comment]
老黄，最近是否有时间看看俄语相关问题呢？
