### ISSUE TITLE
开发自定义词典碰到的问题

### ISSUE THREAD

**Issue by David-Guoo** [ninja33/ODH#300]
您好，谢谢您做了这么棒的插件。我在开发自定义词典的js文件时碰到了一个问题：在Script Name输入了我在服务器上传的js文件url之后，怎样才能确认我是否已经成功加载了我自定义的Script呢？我在下面的栏目以及浏览器右上角的词典选择区域都没有看到自定义的词典。

补充信息：
js文件的class名已经正确修改，在浏览器直接访问这个url可以正确显示我的js文件。另外这个js文件由于只是一个很简短的测试文件，应该没有语法错误。

另外我想请问，如果我只想在本地使用插件，那么在url处输入本地js路径名可行吗？谢谢！

![スクリーンショット 2023-04-14 午後2 25 13](https://user-images.githubusercontent.com/82295508/231961889-9aa72a5e-c883-4de1-acdb-8a9118a67c0c.png)

**Comment by David-Guoo** [comment]
另外，我也点击了Load Scripts 和 Save & Close 的按键

**Comment by ninja33** [comment]
加载后可以词典选项的下拉菜单里看到

<img width="487" alt="image" src="https://user-images.githubusercontent.com/20181220/232180479-6dd4894a-00a5-4d65-9315-9d69c22ef248.png">

我做了一个简单的用于测试的词典，会以中英文两句话，两个颜色显示选中的单词
<img width="544" alt="image" src="https://user-images.githubusercontent.com/20181220/232180657-e2d8814f-1476-40ca-a8e9-accaf10d87ad.png">

脚本的gist地址是 https://gist.github.com/ninja33/021c27dabfdd57c3dae39aa67b138b56
raw 地址是 https://gist.githubusercontent.com/ninja33/021c27dabfdd57c3dae39aa67b138b56/raw/cf56ec9aea2f5f1ced3b85bc5cff2fbf8ef293cc/encn_testdict.js
你可以把raw地址贴进自定义词典的url里，load或者save and close都可以。再打开选项，在词典菜单里可以看到 

注意在你的自定义脚本里的 displayName()里要定义显示名，否则下拉菜单就会用class name来显示这本词典。
<img width="532" alt="image" src="https://user-images.githubusercontent.com/20181220/232180760-3975434c-e076-4fae-9a39-791794fa17d0.png">

**Comment by David-Guoo** [comment]
谢谢！问题已经解决了，似乎和Chrome Extension的一个设置"Allow access to file URLs" 有关系
