### ISSUE TITLE
The UI display logic after adding a word

### ISSUE THREAD

**Issue by serifold** [ninja33/ODH#309]
Edited.

**Comment by ninja33** [comment]
目前，插件通过ankiconnect往anki加单词的时候，是单向通讯，也就是说调用了ankiconnect的addnote接口，然后最多获得一个返回值，是否添加成功。

对于已添加或者未添加的单词，插件并不会去anki那边查询，然后已添加就不显示加号，不添加就显示，不会这样。或者说已经添加了，查询了几次，目前没这个功能。看不懂就查，查了觉得有必要加一下就加，插件的逻辑比较简单和直白。告诉你查了5次还是10次，没考虑过。

这么做一个是出于插件效率，第二个是因为查重这件事其实是在anki做的。anki的browser里也有这个功能。第三，其实你忘了自己学没学过，再添加就是了，因为上下文的原句不同，也不是说以前加过就不能再加。不同人有不同的逻辑，这个留给使用者自己考虑。

**Comment by serifold** [comment]
Thanks, I get it.
