### ISSUE TITLE
goodreads网页划词窗口不消失

### ISSUE THREAD

**Issue by TheKiteRunning** [ninja33/ODH#31]
如题。正常情况下，当鼠标在其它位置单击后，划词窗口会消失。然而在[goodreads](https://www.goodreads.com/)上，该窗口始终存在。

**Comment by ninja33** [comment]
是的，有的网站如goodreads截获了鼠标点击事件，所以插件就无法对该事件做出原有的反应。
在下一版本(0.7)中增加了按ESC键取消窗口的功能。fixed in 2285de66e01be33445cc1b70e5155472b8dde1c8

**Comment by TheKiteRunning** [comment]
Thanks a lot!

**Comment by TheKiteRunning** [comment]
@ninja33 这个问题似乎已经解决了，感谢老黄，并且不妨添加`fixed` label
