### ISSUE TITLE
音标有问题

### ISSUE THREAD

**Issue by sadhen** [ninja33/ODH#32]
版本： 0.6.1 

音标如果是Front，那么Front就只有音标，没有单词
如果是Backend，那么就没有音标了。

我暂时接受Front里面没有单词，然后手动添加，非常感谢这个插件。

**Comment by ninja33** [comment]
请使用 ODH相应模板把，Basic模板才前后两个字段，不能把单词，音标，释义和句子都放进去啊。

模板地址: http://www.laohuang.net/wp-content/uploads/2018/02/ODH.zip

解压后是个anki文件apkg格式的。的在anki 电脑端用import的方式导入这个apkg就可以在词典助手后台选项处选择这个模板了。

**Comment by sadhen** [comment]
感谢
