### ISSUE TITLE
在线词典中，百词斩右上角加“+”号制作Anki卡片总是失败

### ISSUE THREAD

**Issue by lloyar** [ninja33/ODH#33]

**Comment by ninja33** [comment]
试了一下，百词斩脚本可以制卡。你看看后台选项是否映射正确

![image](https://user-images.githubusercontent.com/20181220/40870945-1f4c49ae-6665-11e8-8435-46a62939f0fc.png)

**Comment by Lloyar** [comment]
![image](https://user-images.githubusercontent.com/22740114/40871920-6c8fae10-6677-11e8-832d-addddd3dce28.png)
是需要下载百词斩的模板吗？在你Bolg上面吗？

**Comment by ninja33** [comment]
没有百词斩模版，这个模版就可以了。
你ankiconnect版本已经是6了？你在我博客里下载一个版本5的吧。

**Comment by Lloyar** [comment]
确实是ankiconnect版本的问题，解决啦

**Comment by cooper1x** [comment]
5在哪里下啊，找了半天没有

**Comment by cooper1x** [comment]
百词斩的图片会挂掉
