### ISSUE TITLE
请问如何加载自制词典脚本？

### ISSUE THREAD

**Issue by Edenharder** [ninja33/ODH#40]
能否更加详细地说明如何加载自制js脚本？

1. 本地js脚本应放于何处？
2. 如何利用沙盒技术来挂载外部脚本？

**Comment by ninja33** [comment]
沙盒技术加载脚本是插件自身的功能，这个用户不许关心。
至于js脚本放在何处，可以放在本地的web服务器上，也可以放在免费的网络服务比如gist上，比如像下面这个js脚本
https://gist.github.com/ninja33/83d351965cec83ca26ebc6526383b636
然后把他的raw地址，放在脚本地址栏加载就可以了。
