### ISSUE TITLE
encn_Cambridge的audio url找不到路徑

### ISSUE THREAD

**Issue by ptoyhawinf** [ninja33/ODH#45]
7/25前使用encn_Cambridge腳本還可以下載audio到anki
8/1開始發現無法寫入anki，點選頁面也無法發音
![image](https://user-images.githubusercontent.com/6279891/43561611-47dd0f1a-964a-11e8-8084-8e7d8a2797d6.png)
開啟console發現好像audio路徑都變成網站的網址(google頁面查詢取詞)，如下圖
![image](https://user-images.githubusercontent.com/6279891/43561702-c64e2618-964a-11e8-95e9-760c0bb6fad4.png)

而不是到https://dictionary.cambridge.org/media/english-chinese-simplified/us_pron/s/str/strin/string.mp3 來取得mp3播放
(我猜也是因為這樣沒辦法寫到anki裡)

不知道此狀況是個案還是encn_Cambridge腳本需要調整什麼設定??

**Comment by ninja33** [comment]
谢谢您发觉问题并打开console指出问题所在。

经检查后发现，Cambridge词典网站原先在此处返回的是一个以 `https://`开头的绝对路径，而现在仅返回一个以`/media/...`开头的相对路径，所以当您访问任何网站文章时，ODH都会以那个网站地址拼接相对路径来获取音频文件地址。

现我已将此脚本作了修改，并提交到github。您可在插件后台选项的脚本地址栏位里将原脚本名称`encn_Cambridge`改为`lib://encn_Cambridge`来马上获得脚本更新。否则，需等下一次google web store的插件更新以更新内置脚本。

再次感谢您的反馈。

**Comment by ptoyhawinf** [comment]
你好
已更新完畢，目前Cambridge取詞的功能都正常了，謝謝你那麼快就排除狀況

祝你順心
