### ISSUE TITLE
解釋與例句加粗

### ISSUE THREAD

**Issue by adgjlsfhk123** [ninja33/ODH#5]
您好，我想把ODH搭配之前的antimonn模板使用。
尤其是definition-word的cloze功能。
因此想問能不能再儲存的時候，就直接將句子與解釋中要查詢的單字bold，這樣應該就可以直接使用antimonn模板了

舉例來說，當我用collin en-en查詢debunk的時候，目前ankiconnect會顯示
verb If you debunk a widely held belief, you show that it is false. If you debunk something that is widely admired, you show that it is not as good as people think it is.
Historian Michael Beschloss debunks a few myths. [VERB noun]
...the Frenchmen of the enlightenment who debunked the church and the crown. [VERB noun]
但我希望會是
verb If you **debunk** a widely held belief, you show that it is false. If you debunk something that is widely admired, you show that it is not as good as people think it is.
Historian Michael Beschloss **debunk**s a few myths. [VERB noun]
...the Frenchmen of the enlightenment who **debunk**ed the church and the crown. [VERB noun]

謝謝您。

**Comment by adgjlsfhk123** [comment]
另一種配套方式是使用劃詞助手，再逐卡刪除中文字，但缺點是definition word缺少collins的例句

**Comment by ninja33** [comment]
谢谢你的建议。
ODH原来不是刻意给使用anki或者使用antimoon模板的人设计的。所以没有考虑到这点。
好在ODH的脚本是可以外挂加载的。你可以自己改改那个enen_Collins的脚本，基本上也就是用正则表达式把解释和例句中的单词匹配出来外加<b>标签。或者等我下一次更新时把相应脚本更新了。

**Comment by adgjlsfhk123** [comment]
謝謝回覆，我在台灣使用collins en-en，也大致上要等2~3秒。其他詞典也是會稍微快一點。
再麻煩您了。再次感謝。

**Comment by ninja33** [comment]
这个插件目前支持英文，简体，繁体三种界面语言。不知道你看到的是不是繁体。目前的繁体，只是简体词语的繁体话，未必符合繁体中文地区的使用习惯，比如据我所知，单词在台湾称为单字。如果在界面上有何不符合使用习惯的地方，还望指出。谢谢。

**Comment by adgjlsfhk123** [comment]
看到的是繁體沒錯，謝謝你慷慨、體貼的考量。

我習慣使用辭典或字典，但詞典似乎也有人用。
插件有人使用，也有翻譯為附加元件、擴充套件或者外掛。
熱鍵通常翻譯成快捷鍵 。
模板，在 anki中是顯示為類型，是type的直接翻譯，但只寫類型容易不知所云，如果翻譯成卡片類型又有點太冗餘，因此我覺得模板是不錯的翻譯。
音頻很少見，我會翻譯成音檔。
激活之前不常見，但最近幾年還算常見，我會翻譯成啟動、開啟。
Collins似乎沒有引進台灣，因此似乎沒有台灣的翻譯版本。
以上供您參考。

**Comment by adgjlsfhk123** [comment]
說來慚愧，本來想要自己嘗試寫看看，但還是寫不出來。如果您有空，再麻煩你幫忙加粗單字了。

**Comment by ninja33** [comment]
fixed in commit 47d905a

柯林斯英汉和英英两本词典已经改好，内置脚本要在下一版随插件一起发布。
你可以用外置脚本(在脚本地址前加上lib://)先使用起来，即在脚本地址栏输入：
`lib://enen_Collins, lib://encn_Collins`

![image](https://user-images.githubusercontent.com/20181220/37210986-732c0144-23e5-11e8-9ee2-11874202467e.png)


![image](https://user-images.githubusercontent.com/20181220/37211138-ea5d78b0-23e5-11e8-9d5b-f8b0ea89709e.png)

**Comment by adgjlsfhk123** [comment]
十分感謝！
