### ISSUE TITLE
OLCC四合一词典脚本无法加载

### ISSUE THREAD

**Issue by Oosl** [ninja33/ODH#50]
#### 已经在设置中正确添加encn_List项，但是始终加载不出来，其他同样步骤添加的有道词典脚本等就可以正常加载。
![](https://ws1.sinaimg.cn/large/006aqgABgy1fusq16xka6j30ax07yaaj.jpg)

**Comment by ninja33** [comment]
四合一脚本里的朗文词典已经失效了。所以就打散成柯林斯，牛津和剑桥三本词典了。初始状态下剑桥词典并未显示，是因为剑桥词典的源网站在海外，时延较大，所以脚本列表里没包含。如果需要的话，在列表结尾加 `encn_Cambridge` 就可以了(记得脚本名称间用逗号分割)。

**Comment by Oosl** [comment]
哦哦，原来是这样，我的问题解决了，谢谢您的及时解答。另外这个东西真的很好用，再次感谢你的付出，嘿嘿。
