### ISSUE TITLE
自带脚本encn-collins选词数量的问题

### ISSUE THREAD

**Issue by HoollyFox** [ninja33/ODH#6]
以address 为例，即少了“处理”义项，不知是什么原因？

参考页面：https://www.collinsdictionary.com/dictionary/english-chinese/address

**Comment by ninja33** [comment]
谢谢你的反馈。encn_Collins 取的是有道的数据源。所以和相应网络数据源中显示的是一致的。
你说的address这个单词的情况，可以去查阅下面有道翻译的查询界面，选择下面“ 柯林斯英汉双解大词典 ”这个tab里返回结果。[http://dict.youdao.com/w/eng/address/#keyfrom=dict2.index](http://dict.youdao.com/w/eng/address/#keyfrom=dict2.index)

**Comment by HoollyFox** [comment]
原来是这样，抱歉没认真考虑原始地址。谢谢解答！
