### ISSUE TITLE
可以在用chrome打开的pdf 文件里取词吗

### ISSUE THREAD

**Issue by oilbottle** [ninja33/ODH#60]
自己试了不行，不知道是不是只有我这样。

能不能添加这个功能呢？这样的话看文献会很方便啊

**Comment by ninja33** [comment]
要用pdf.js 打开才可以。你可以去网上搜索一下有关pdf.js的信息。记得插件后台另外还需要在“允许访问本地文件”选项前打勾。

**Comment by oilbottle** [comment]
谢谢老黄！我试用了chrome里的pdf.js插件。确定“允许访问本地文件”已经打勾了。用pdf.js打开pdf后依然不能取词。
我用了官方文档里的demo https://mozilla.github.io/pdf.js/web/viewer.html 这个试可以取词的。

pdf.js的作用是把pdf转化成html吗？我注意到用chrome上的插件打开后，后缀还是pdf，不知道是不是这个原因呢？
系统是最新win10，最新chrome

![image](https://user-images.githubusercontent.com/19664570/50545288-7fabbb00-0bc3-11e9-8236-5d578f893346.png)
这个是地址栏的截图，希望能有帮助

**Comment by ninja33** [comment]
嗯，用官方demo来打开你本地的PDF把。那个插件我不太清楚。

**Comment by oilbottle** [comment]
了解了，谢谢老黄！
________________________________
