### ISSUE TITLE
为什么直接从本地打开pdf reader(pdf.js)可以划词但是用插件打开就不能划词

### ISSUE THREAD

**Issue by qjgods** [ninja33/ODH#62]
插件地址：
https://add0n.com/pdf-reader.html

从插件打开就不能划词：
chrome-extension://ieepebpjnkhaiioojkepfniodjmjjihl/data/pdf.js/web/viewer.html

从本地打开可以划词：
file:///C:/Users/35846/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ieepebpjnkhaiioojkepfniodjmjjihl/0.1.2_1/data/pdf.js/web/viewer.html

**Comment by ninja33** [comment]
插件之间未经允许是不可以访问数据。而由本地文件打开后，等同于本地文件访问，这个是在后台选项处勾选了本地文件访问权限所允许了的。

当然这个只是我的猜想。因为划词插件本来就是为网页开发，你用其他插件将pdf转换成网页后划词不成功，为什么会这样，我也不知道。

**Comment by qjgods** [comment]
好吧，确实是因为没有权限操作。看来只能用本地的版本了。
