### ISSUE TITLE
添加单词所在半句作为例句

### ISSUE THREAD

**Issue by Edenharder** [ninja33/ODH#65]
有时一整句话是由很多个被逗号隔开的半句组成，这样整个句子就显得特别冗长。能否增加选项使得能够只添加单词所在半句作为例句呢？或者是添加一个单词所在句长度的上限，有时只看单词附近其他单词就够理解背景了。

**Comment by ninja33** [comment]
自动判断截取句子总是不那么准确，或者并不能满足不同人的要求。等下一版本例句可编辑，就可以在保存前自行修改了

**Comment by Edenharder** [comment]
嗯，的确是很难判断一整句话，尤其是有数字的时候。但希望下一版本例句可编辑时，能够有两个给懒人的选项：1. 截取句号`.`间的句子当例句；2. 截取逗号`,`间的句子当例句。这样就不用每个例句都修改了。
