### ISSUE TITLE
Shift取词导致跳出光标

### ISSUE THREAD

**Issue by HoollyFox** [ninja33/ODH#7]
如果打开ODH并且选择Shift取词，在web文本输入框中，按下Shift光标即消失，此情况在Anki划词助手中并未发生

**Comment by ninja33** [comment]
ODH为了处理多个单词，既词组和惯用法的翻译，主要以“选中文本”作为输入(因为用户可以用鼠标划取任意数量单词形成词组)，而不是像anki划词助手那样主要以自动取词为主。

因此ODH不处理文本框，按钮，多选单选框等表单元素中的文字。因为试图双击或者单击划取那些元素上的文本，会造成点击操作而发生跳转。

简单而言你碰到的这种情况就是，ODH虽然探测到你按了shift，但是他判断是一个表单元素，他就放弃不做处理了。

**Comment by HoollyFox** [comment]
看了你的说明，我理解了其中的机制，可以把这样的情况归结为“为了取词的多词性而做的妥协”。

只是有的时候觉得很不方便，不能理解为什么光标会突然消失，包括组合键位也会造成这种情况（比如Ctrl+Shift 更改输入法，也会导致光标消失，而重新选择文本框，输入法也仍是原来的输入法），一般这样的时候，我就只能关闭插件。

**Comment by ninja33** [comment]
是的。词典助手比较适用的情况是较少输入而连续沉浸式阅读的情况，在弹窗看完释义乃至一键制卡后，继续阅读。

他并非在写作时用于完整词典查询的替代，适合网页或者html格式小说的阅读。
