### ISSUE TITLE
内置词典能否提供简单释义

### ISSUE THREAD

**Issue by atjason** [ninja33/ODH#70]
首先感谢提供插件。

之前在用划词助手，现在切换到 ODH，发现没有 glossary，也即简单释义、不包含例句等更多信息，如 run: (v) 跑步

请问是内置词典本身没有这个字段，或者是我操作不对？试了 Difinition 和 Difinitions，发现都是大段那么样式。谢谢。

**Comment by ninja33** [comment]
简单释义放在一个单独的有道简明词典里了。那是本网络词典，混在离线词典里，会极大的影响离线词典的使用。离线词典本身就是为了在没有网络的时候，依然能够让用户使用插件。

另外，每个网络权威词典(如：柯林斯，牛津，剑桥)尾部，如果词典本身的解释找不到，也会用简单释义替代。也就是说，词典查找的优先级是 权威词典>简明词典>整句翻译。但是不再会以权威解释+简单解释这种混合方式。但因为权威词典本身也是网络词典，后面附件网络简明词典的话并不影响。也就是说网络词典，不管是权威词典还是简明词典，要能用就都能用，没网络时，就都不能用。

definition是指如果一个单词有一词多义的情况，那么只会记录你点击加号的那一个解释。
definitions是指，不管你点的哪个加号，该单词的所有解释，都会记录在你指定的字段里。
但是不管是definition还是definitions，都是从权威词典里摘录的内容，简明词典是没有这种区分的，因为它往往只有一整段，并不区分一词多义。

**Comment by ninja33** [comment]
另外想说明的是，有道简明词典的数据源和网络柯林斯英汉双解是一个，都是有道。
所以，如果在有网络的情况下，可以使用柯林斯英汉双解(不是内置的那本)

**Comment by atjason** [comment]
你好，谢谢你回复如此之快。

1. 我的感觉是，definition 中不仅包含示意，而是把整个信息包含进来了。请看看我下面的截图：

![](https://ws3.sinaimg.cn/large/006tKfTcgy1g09skzyasvj30qa0n846k.jpg)

![](https://ws2.sinaimg.cn/large/006tKfTcgy1g09sl7gw0hj30n40hi7bl.jpg)

![](https://ws2.sinaimg.cn/large/006tKfTcgy1g09sl7gw0hj30n40hi7bl.jpg)

2. 我试了有道，相对来说是最简洁的了。

3. 最后，这是我之前用划词助手时生成的样式，也是我想在 ODH 中实现的样式。除了有道，是不是没有更好的做法了？

![](https://ws1.sinaimg.cn/large/006tKfTcgy1g09sm69gl9j315809qtas.jpg)

**Comment by ninja33** [comment]
是的。释义就是指带词性，中文解释，英文解释，中文例句，英文例句这五项的全部内容。在一本词典里，当你查一个词头(heads word)时，这五项是必须的。那么简明词典基本上只含了词性喝中文解释这两项。

如果想达到你演示的效果，就用简明词典好了。但长期学习，我建议你用权威词典，从双解慢慢过渡到英英。

最后我看你的卡片模板是做了一定的设计的，如果是你自己做的，表明你有一定的html和css网页制作的知识。那么你可以用css里的display:none 来把释义里五项的任意一项隐藏起来。他们的css class分别是
词性：pos
中文解释：chn_tran
英文解释：eng_tran
中文例句：chn_sent
英文例句：eng_sent

只要把相应的 css class设成隐藏就可以了。

**Comment by atjason** [comment]
明白了，谢谢解释。

恩，样式是我自己设计的，我试按你的提示隐藏其它项（简单词典的问题在于，目前它是一个词性一行，略啰嗦）。甚至，我都觉得隐藏这几项，全凭例句来记单词了。
