### ISSUE TITLE
Add a hotkey for toggling scanning on/off

### ISSUE THREAD

**Issue by Panintelize** [ninja33/ODH#83]
For now two clicks are needed for this, a hotkey would be extremely helpful.
![image](https://user-images.githubusercontent.com/24824399/56410572-0ff23680-626d-11e9-8a08-bb222186e51c.png) 

![image](https://user-images.githubusercontent.com/24824399/56410601-26988d80-626d-11e9-8e55-9aa782062398.png)

**Comment by ninja33** [comment]
will add this function on next version.
you may check code based on other forks first https://github.com/Indeity/ODH/commit/729ee66e8a72d4ed2b07459fffdd39f0150620e2

**Comment by ninja33** [comment]
added Alt+Q as hot key to toggle On/Off at commit 2e8a399
