### ISSUE TITLE
ankiconnect 连接不稳定

### ISSUE THREAD

**Issue by Zilong-Li** [ninja33/ODH#87]
你好，我在mac chrome上使用ODH时，发现连接ankiconnect一直不稳定。确切的说是每切换一个新的网页，就连不上了，这时需要手动打开anki随便点击一下就又可以了。之前一直使用的anki划词助手，从没出现这种问题（PS: 二者没有同时打开）。

**Comment by ninja33** [comment]
这个应该是ankiconnect在macOs上的问题。你可以去看看ankiconnect作者提到的有关解决办法。

https://foosoft.net/projects/anki-connect/#notes-for-mac-os-x-users

**Comment by Zilong-Li** [comment]
解决了！感谢老黄！
参照以上链接的建议，打开终端执行以下命令：
`defaults write net.ankiweb.dtop NSAppSleepDisabled -bool true
defaults write net.ichi2.anki NSAppSleepDisabled -bool true
defaults write org.qt-project.Qt.QtWebEngineCore NSAppSleepDisabled -bool true`

**Comment by Zilong-Li** [comment]
解决了！感谢老黄！
参照以上链接的建议，打开终端执行以下命令：
`defaults write net.ankiweb.dtop NSAppSleepDisabled -bool true

defaults write net.ichi2.anki NSAppSleepDisabled -bool true

defaults write org.qt-project.Qt.QtWebEngineCore NSAppSleepDisabled -bool true`

**Comment by Zilong-Li** [comment]
解决了！感谢老黄！
参照以上链接的建议，打开终端执行以下命令：
defaults write net.ankiweb.dtop NSAppSleepDisabled -bool true

defaults write net.ichi2.anki NSAppSleepDisabled -bool true

defaults write org.qt-project.Qt.QtWebEngineCore NSAppSleepDisabled -bool true

**Comment by Sandural** [comment]
额, 我终端输入了, 但是链接还是会断...为什么啊?

**Comment by dancewhale** [comment]
注意该命令只能用普通用户执行,不能用su用户执行.
我之前想当然的用su用户执行,结果执行结果对普通用户执行的anki不生效.
