### ISSUE TITLE
添加后在anki上音频无法播放

### ISSUE THREAD

**Issue by YiQ-Zhao** [ninja33/ODH#88]
你好，老黄。我在取词时也可以听到音频，我添加之后如何在复习的时候可以自动播放音频？是否是我自己的设置错误？
![image](https://user-images.githubusercontent.com/22917705/56883244-eed2d800-6a1a-11e9-95ad-eb77d3033abd.png)
请问这个路径是指向哪里的？我看链接是直接指向网络音频地址的。我试过collins(build in) 也无法播放，试过replay audio也没有声音。不好意思如果问的问题太简单了

**Comment by ninja33** [comment]
你如果用的是我博客里的odh模板，目前音频不是自动播放的，而是点击卡片正面空白处播放。

**Comment by YiQ-Zhao** [comment]
谢谢及时回复，我之前套用了自己手动创建的模板。
感谢，可以用了
！
