### ISSUE TITLE
使用 macos 打开 anki 和这个插件有时候不能连接

### ISSUE THREAD

**Issue by Aifcce** [ninja33/ODH#99]
打开 anki 后，插件能够正确识别 anki 可以添加卡片，　此时将　anki　放在后台运行，一会后就不能连接了。点击 anki 将程序放在前排，又能够正确的连接。我感觉是 macos 的系统机制让 anki 的插件休眠了。有什么办法能够解决吗？

**Comment by ninja33** [comment]
这个问题在issue列表有人问过，你自己查一下吧。

**Comment by Aifcce** [comment]
好的　谢了
